//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PDV.Task1._0.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public int UsersID { get; set; }
        public string FirstName { get; set; }
        public string LastrName { get; set; }
        public int RoleID { get; set; }
    
        public virtual Role Role { get; set; }
    }
}
